#!/bin/bash

if [ x"$KAGAKUBINRANTOPDIR" == x"" ]; then 

export KAGAKUBINRANTOPDIR=/home/maho/AdaptVQE
export KAGAKUBINRANARCHIVESDIR=$KAGAKUBINRANTOPDIR/archives
export KAGAKUBINRANSETUPDIR=$KAGAKUBINRANTOPDIR/setup
export KAGAKUBINRANPKGDIR=$KAGAKUBINRANTOPDIR/pkg
export KAGAKUBINRANSCRIPTSDIR=$KAGAKUBINRANTOPDIR/scripts
export KAGAKUBINRANTMPDIR=$KAGAKUBINRANTOPDIR/tmp
export PATH=$KAGAKUBINRANPKGDIR/bin:$KAGAKUBINRANPKGDIR/openbabel/bin:$KAGAKUBINRANPKGDIR/psi4/bin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin
export LD_LIBRARY_PATH=$KAGAKUBINRANPKGDIR/lib:$KAGAKUBINRANPKGDIR/lib64:$LD_LIBRARY_PATH
export LDFLAGS="-L$KAGAKUBINRANPKGDIR/lib -L$KAGAKUBINRANPKGDIR/lib64"
export PYTHONPATH=$KAGAKUBINRANPKGDIR/lib64/python3.8/site-packages:$KAGAKUBINRANPKGDIR/psi4:$KAGAKUBINRANPKGDIR/lib/python3.8/site-packages:$PYTHONPATH
export CC=$KAGAKUBINRANPKGDIR/bin/gcc
export CXX=$KAGAKUBINRANPKGDIR/bin/g++
export F77=$KAGAKUBINRANPKGDIR/bin/gfortran
export FC=$KAGAKUBINRANPKGDIR/bin/gfortran
export EDITOR=ng

alias clean='rm -f *~ \#* Gau-*'

fi
