VERSION=0.3.10

WRKDIR=$KAGAKUBINRANSETUPDIR/work_openblas
rm -rf $WRKDIR
mkdir $WRKDIR

cd $WRKDIR
tar xvfz $KAGAKUBINRANARCHIVESDIR/OpenBLAS-${VERSION}.tar.gz
cd OpenBLAS-${VERSION}
make DYNAMIC_ARCH=1
make DYNAMIC_ARCH=1 PREFIX=$KAGAKUBINRANPKGDIR install

cd $KAGAKUBINRANSETUPDIR
rm -rf $WRKDIR
